#spring:
#  #  autoconfigure:
#  #    exclude:
#  #      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  cloud:
#    config:
#      uri: http://localhost:8888
#  application:
#    name: storeConfidDB
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: validate
#     show-sql: true
#   datasource:
#     url: jdbc:postgresql://localhost:5432/shop
#     username: admin
#     password: 52669
#   flyway:
#     baseline-on-migrate: true

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:${DATABASE_PATH}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org.springframework.web: debug
    org.springframework.ws: debug
